---
title: "nycanalysis"
author: "Drazzel Feliu"
date: "4/19/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r library_load}
rm(list = ls())

library(tidyverse)
library(sf)
library(viridis)
library(leaflet)
library(maps)
library(htmlwidgets)
library(tidycensus)
library(htmltools)
library(tigris)
library(reshape2)

options(tigris_use_cache = TRUE)
```

```{r codebook_build}
codebook <- load_variables(2017,"acs5")
```

```{r shapefiles}
boroughboundaries <- get_acs(geography = "county",
        variables = "B19013_001",
        state = "NY",
        county = c("New York","Kings","Queens","Bronx","Richmond"),
        geometry = T,
        year = 2017)

nycdata <- get_acs(geography = "tract",
        variables = "B19013_001",
        state = "NY",
        county = c("New York","Kings","Queens","Bronx","Richmond"),
        geometry = T,
        year = 2017,
        cb = FALSE)
```

```{r clean_shapefiles}
st_erase <- function(x, y) {
  st_difference(x, st_union(st_combine(y)))
  }

mh_water <- area_water("NY", "New York", class = "sf")
bx_water <- area_water("NY", "Bronx", class = "sf")
bk_water <- area_water("NY", "Kings", class = "sf")
qu_water <- area_water("NY", "Queens", class = "sf")
si_water <- area_water("NY", "Richmond", class = "sf")

ny_water <- rbind(mh_water,bx_water,bk_water,qu_water,si_water)

nycdata2 <- st_erase(nycdata, ny_water)

boroughboundaries <- st_erase(boroughboundaries, ny_water)
```

```{r append_color_shapefiles_function}
nyccolor <- colorNumeric(
  palette = "magma",
  domain = nycdata2$estimate)
```

```{r load_housing data}
housingdata <- read.csv("Housing_New_York_Units_by_Building.csv")
glimpse(housingdata)
```

```{r leaflet_option_indices}
nycdatahighlights <- highlightOptions(
  weight = 4.5,
  color = "#ffffff",
  fillOpacity = .5,
  bringToFront = TRUE)

nycdatalabeloptions <- labelOptions(
  style = list("font-weight" = "normal", padding = "3px 8px"),
  textsize = "15px",
  direction = "auto")
```

```{r labels, results='hide'}
nycdatalabels <- sprintf(
  paste0(
  "<strong>Name: </strong>%s<br/>",
  "<strong>Median Income in 2017: </strong>%g"),
  nycdata2$NAME,
  nycdata2$estimate
  ) %>% 
  lapply(HTML)
```

```{r popups}
housingdatalabels <- sprintf(
  paste0(
  "<strong>Project Name: </strong>%s<br/>",
  "<strong>Address: </strong>%s<br/>",
  "<strong># of Available Extremely Low Income Units: </strong>%g<br/>",
  "<strong># of Available Very Low Income Units: </strong>%g<br/>",
  "<strong># of Available Low Income Units: </strong>%g<br/>",
  "<strong># of Available Moderate Income Units: </strong>%g<br/>",
  "<strong># of Available Middle Income Units: </strong>%g<br/>",
  "<strong># of Available Other Income Units: </strong>%g<br/>",
  "<strong># of Available Rental Units: </strong>%g<br/>"),
  housingdata$Project.Name,
  as.character(paste0(housingdata$Number,sep=" ",housingdata$Street)),
  housingdata$Extremely.Low.Income.Units,
  housingdata$Very.Low.Income.Units,
  housingdata$Low.Income.Units,
  housingdata$Moderate.Income.Units,
  housingdata$Middle.Income.Units,
  housingdata$Other.Income.Units,
  housingdata$Counted.Rental.Units
  ) %>% 
  lapply(HTML)
```

```{r housing_data}
housingcolor <- colorBin(
  palette = "viridis",
  domain = housingdata$Counted.Rental.Units,
  bins = c(0,50,100,150,200,1000),
  right = T)

getRadius <- function(housingdata) {
  sapply(housingdata$Counted.Rental.Units, function(Counted.Rental.Units) {
  if(Counted.Rental.Units >=200)  {
    10
  } else if(Counted.Rental.Units >= 100) {
    7.5
  } else {
    5
  }  })
}
```

```{r add_race_variable}
racecodebook <- codebook %>% filter(str_detect(label,"race")) %>% filter(str_detect(label,"Population of one")) %>%
  mutate(names="name", count=1:7, merge=paste(names,count, sep="")) %>% select(-c(names,count))

racedataindi <- get_acs(geography = "tract",
        variables = unlist(racecodebook$name),
        state = "NY",
        county = c("New York","Kings","Queens","Bronx","Richmond"),
        geometry = T,
        year = 2017,
        cb = FALSE)

racedata <- racedataindi %>% filter(variable!="C02003_002") %>% group_by(GEOID) %>% mutate(sum=sum(estimate)) %>%
  mutate(percent=estimate/sum(estimate))

racedata <- merge(racedata,racecodebook[c(1,2)],by.x="variable",by.y="name") %>% select(-variable) %>%
  mutate(label=str_remove(label,"Estimate!!Total!!Population of one race!!")) %>% group_by(GEOID) %>% arrange(GEOID)

racedata <- racedata %>% 
  select(-c(moe,estimate,sum)) %>% 
  mutate(percent=replace_na(percent,0)) %>% 
  spread(label,percent) %>% arrange(GEOID)
  
#CLEAN SHAPEFILES
racedata <- st_erase(racedata,ny_water)
```

```{r mapping_race_variables}
racedatahighlights <- highlightOptions(
  weight = 4.5,
  color = "#ffffff",
  fillOpacity = .5,
  bringToFront = TRUE)

racedatalabeloptions <- labelOptions(
  style = list("font-weight" = "normal",padding = "3px 8px"),
  textsize = "15px",
  direction = "auto"
)

racedatalabels <- sprintf(
  paste0(
    "<strong>Name:</strong> %s<br/>",
    "<strong>Race:</strong> White - %g%%<br/>",
    "<strong>Race:</strong> Black - %g%%<br/>",
    "<strong>Race:</strong> Asian - %g%%<br/>",
    "<strong>Race:</strong> American Indian - %g%%<br/>",
    "<strong>Race:</strong> Native Hawaiian - %g%%<br/>",
    "<strong>Race:</strong> Other - %g%%<br/>"),
  racedata$NAME,
  round(racedata$White,2)*100,
  round(racedata$`Black or African American`,2)*100,
  round(racedata$`Asian alone`,2)*100,
  round(racedata$`American Indian and Alaska Native`,2)*100,
  round(racedata$`Native Hawaiian and Other Pacific Islander`,2)*100,
  round(racedata$`Some other race`,2)*100
  ) %>% lapply(HTML)

```

```{r}
map <- leaflet() %>% setView(lng = -74.0060, lat = 40.7128, zoom = 11) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = st_geometry(boroughboundaries),
              fillColor = NULL,
              color = "black",
              weight = 2.5,
              fillOpacity = .001,
              smoothFactor = .2
              ) %>% 
  addPolygons(data=st_geometry(nycdata2),
              fillColor = nyccolor(nycdata2$estimate),
              color = "magma",
              weight= .3,
              smoothFactor = .2,
              fillOpacity = .55,
              popup  = nycdatalabels,
              popupOptions = nycdatalabeloptions,
              group = "Income",
              highlightOptions = nycdatahighlights
  ) %>% 
  addPolygons(data = st_geometry(racedata),
              fillColor = NULL,
              color = "black",
              weight = 1,
              fillOpacity = .01,
              smoothFactor = .2,
              popup  = racedatalabels,
              popupOptions = racedatalabeloptions,
              highlightOptions = racedatahighlights,
              group = "Race"
              ) %>% 
  addLegend(title = "Median Income",
            pal = nyccolor,
            values = nycdata2$estimate,
            position = "topright",
            group="Income") %>% 
  addCircleMarkers(housingdata$Longitude, 
                   housingdata$Latitude,
                   color = housingcolor(housingdata$Counted.Rental.Units),
                   radius = getRadius(housingdata),
                   stroke = FALSE,
                   fillOpacity = .5,
                   label = housingdatalabels,
                   group = "Housing") %>% 
  addLegend(title = "Number of Units Available",
            pal = housingcolor,
            values = housingdata$Counted.Rental.Units,
            position = "topright",
            group = "Housing") %>% 
  addLayersControl(
    overlayGroups = c("Income", "Housing","Race"),
    position = "bottomright")
```

```{r}
saveWidget(map,"index.html")
```


```{r data_analysis}
nycdata3 <- nycdata2
racedata2 <- racedata

nycdata3$geometry <- NULL
racedata2$geometry <- NULL


datanalysis <- merge(nycdata3,racedata2[(c(1,3:8))],by.x="GEOID",by.y = "GEOID")

cor.test(datanalysis$estimate,datanalysis$White,method= c("pearson"))
cor.test(datanalysis$estimate,datanalysis$`American Indian and Alaska Native`,method= c("pearson"))
cor.test(datanalysis$estimate,datanalysis$`Asian alone`,method= c("pearson"))
cor.test(datanalysis$estimate,datanalysis$`Black or African American`,method= c("pearson"))
cor.test(datanalysis$estimate,datanalysis$`Native Hawaiian and Other Pacific Islander`,method= c("pearson"))
cor.test(datanalysis$estimate,datanalysis$`Some other race`,method= c("pearson"))
```

